/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myearseditor.View;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import myearseditor.controller.RequirementFile;

/**
 *
 * @author Krish
 */
public class Initial extends javax.swing.JFrame {

    /**
     * Creates new form Initial
     */
    public Initial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        _AddReqBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        _DelReqBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        _FileMenu = new javax.swing.JMenu();
        _newFileItem = new javax.swing.JMenuItem();
        _openFileItem = new javax.swing.JMenuItem();
        _saveFileItem = new javax.swing.JMenuItem();
        _saveAsFileItem = new javax.swing.JMenuItem();
        _exitFileItem = new javax.swing.JMenuItem();
        _ToolsMenu = new javax.swing.JMenu();
        _NavigationMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("myEarsEditor");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(640, 492));

        jToolBar1.setRollover(true);

        _AddReqBtn.setText("New Req");
        _AddReqBtn.setFocusable(false);
        _AddReqBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _AddReqBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(_AddReqBtn);

        jLabel1.setText(" ");
        jToolBar1.add(jLabel1);

        _DelReqBtn.setText("Delete");
        _DelReqBtn.setFocusable(false);
        _DelReqBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _DelReqBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(_DelReqBtn);

        jLabel2.setText(" ");
        jToolBar1.add(jLabel2);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _FileMenu.setText("File");

        _newFileItem.setText("New");
        _newFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _newFileItemActionPerformed(evt);
            }
        });
        _FileMenu.add(_newFileItem);

        _openFileItem.setText("Open");
        _FileMenu.add(_openFileItem);

        _saveFileItem.setText("Save");
        _FileMenu.add(_saveFileItem);

        _saveAsFileItem.setText("Save As..");
        _FileMenu.add(_saveAsFileItem);

        _exitFileItem.setText("Exit");
        _FileMenu.add(_exitFileItem);

        jMenuBar1.add(_FileMenu);

        _ToolsMenu.setText("Tools");
        jMenuBar1.add(_ToolsMenu);

        _NavigationMenu.setText("Navigation");
        jMenuBar1.add(_NavigationMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("untitled");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void _newFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__newFileItemActionPerformed
        // TODO add your handling code here:
        BasePanel newPanel = new BasePanel();
        RequirementFile _Reqfile = new RequirementFile(newPanel);
        JScrollPane _scrollPane = new JScrollPane(_Reqfile._reqPanel);
        _scrollPane.setAutoscrolls(true);
        JPanel scrollPanel = new JPanel();
        scrollPanel.add(_scrollPane);
        //scrollPanel.setSize(640,480);
        scrollPanel.setAutoscrolls(true);
        jTabbedPane1.addTab("untitled",scrollPanel);           
    }//GEN-LAST:event__newFileItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Initial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _AddReqBtn;
    private javax.swing.JButton _DelReqBtn;
    private javax.swing.JMenu _FileMenu;
    private javax.swing.JMenu _NavigationMenu;
    private javax.swing.JMenu _ToolsMenu;
    private javax.swing.JMenuItem _exitFileItem;
    private javax.swing.JMenuItem _newFileItem;
    private javax.swing.JMenuItem _openFileItem;
    private javax.swing.JMenuItem _saveAsFileItem;
    private javax.swing.JMenuItem _saveFileItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
