/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iiitbEarsEditor.View;

/**
 *
 * @author Krish
 */
public class DefaultFrame extends javax.swing.JFrame {

    /**
     * Creates new form DefaultFrame
     */
    public DefaultFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        _toolbarItem = new javax.swing.JToolBar();
        _addReqBtn = new javax.swing.JButton();
        _AddDelSpaceLbl = new javax.swing.JLabel();
        _delReqBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        _defaultFrameMenu = new javax.swing.JMenuBar();
        _fileMenu = new javax.swing.JMenu();
        _newFileItem = new javax.swing.JMenuItem();
        _openFileItem = new javax.swing.JMenuItem();
        _saveFileItem = new javax.swing.JMenuItem();
        _saveAsFileItem = new javax.swing.JMenuItem();
        _closeFileItem = new javax.swing.JMenuItem();
        _exitItem = new javax.swing.JMenuItem();
        _editMenu = new javax.swing.JMenu();
        _toolsMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _toolbarItem.setBorder(null);
        _toolbarItem.setRollover(true);

        _addReqBtn.setText("Add Req.");
        _addReqBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _addReqBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        _toolbarItem.add(_addReqBtn);

        _AddDelSpaceLbl.setText("  ");
        _toolbarItem.add(_AddDelSpaceLbl);

        _delReqBtn.setText("Delete");
        _delReqBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _delReqBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        _delReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _delReqBtnActionPerformed(evt);
            }
        });
        _toolbarItem.add(_delReqBtn);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jScrollPane1.setViewportView(jTabbedPane1);

        _fileMenu.setText("File");

        _newFileItem.setText("New");
        _fileMenu.add(_newFileItem);

        _openFileItem.setText("Open");
        _fileMenu.add(_openFileItem);

        _saveFileItem.setText("Save");
        _fileMenu.add(_saveFileItem);

        _saveAsFileItem.setText("Save as..");
        _fileMenu.add(_saveAsFileItem);

        _closeFileItem.setText("Close");
        _fileMenu.add(_closeFileItem);

        _exitItem.setText("Exit");
        _fileMenu.add(_exitItem);

        _defaultFrameMenu.add(_fileMenu);

        _editMenu.setText("Edit");
        _defaultFrameMenu.add(_editMenu);

        _toolsMenu.setText("Tools");
        _defaultFrameMenu.add(_toolsMenu);

        setJMenuBar(_defaultFrameMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_toolbarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_toolbarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _delReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__delReqBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__delReqBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaultFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _AddDelSpaceLbl;
    private javax.swing.JButton _addReqBtn;
    private javax.swing.JMenuItem _closeFileItem;
    private javax.swing.JMenuBar _defaultFrameMenu;
    private javax.swing.JButton _delReqBtn;
    private javax.swing.JMenu _editMenu;
    private javax.swing.JMenuItem _exitItem;
    private javax.swing.JMenu _fileMenu;
    private javax.swing.JMenuItem _newFileItem;
    private javax.swing.JMenuItem _openFileItem;
    private javax.swing.JMenuItem _saveAsFileItem;
    private javax.swing.JMenuItem _saveFileItem;
    private javax.swing.JToolBar _toolbarItem;
    private javax.swing.JMenu _toolsMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
