/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iiitbEarsEditor.View;

import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import test.JButtonTableExample;

/**
 *
 * @author michael
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
     static TabUI tu = new TabUI();
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        new_req = new javax.swing.JButton();
        del_req = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        new_FileMenu = new javax.swing.JMenuItem();
        open_FileMenu = new javax.swing.JMenuItem();
        save_FileMenu = new javax.swing.JMenuItem();
        saveAs_FileMenu = new javax.swing.JMenuItem();
        close_FileMenu = new javax.swing.JMenuItem();
        exit_FileMenu = new javax.swing.JMenuItem();
        edit_menu = new javax.swing.JMenu();
        tools_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        new_req.setText("New Requirement");
        new_req.setFocusable(false);
        new_req.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        new_req.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        new_req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_reqActionPerformed(evt);
            }
        });
        jToolBar1.add(new_req);

        del_req.setText("Delete Requirement");
        del_req.setFocusable(false);
        del_req.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        del_req.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(del_req);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Navigation", "Next red requirement", "Prev red requirement", "Next grey requirement", "Prev grey requirement", "Next green requirement", "Prev green requirement" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(57, 37));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(57, 37));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));
        jTabbedPane1.addTab("File 1", jPanel2);

        jScrollPane1.setViewportView(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("File 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        file_menu.setText("File");

        new_FileMenu.setText("New");
        new_FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_FileMenuActionPerformed(evt);
            }
        });
        file_menu.add(new_FileMenu);

        open_FileMenu.setText("Open");
        file_menu.add(open_FileMenu);

        save_FileMenu.setText("Save");
        file_menu.add(save_FileMenu);

        saveAs_FileMenu.setText("Save As");
        file_menu.add(saveAs_FileMenu);

        close_FileMenu.setText("Close");
        file_menu.add(close_FileMenu);

        exit_FileMenu.setText("Exit");
        file_menu.add(exit_FileMenu);

        jMenuBar1.add(file_menu);

        edit_menu.setText("Edit");
        jMenuBar1.add(edit_menu);

        tools_menu.setText("Tools");
        jMenuBar1.add(tools_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_FileMenuActionPerformed
        // TODO add your handling code here:
        
        //JButtonTableExample ex = new JButtonTableExample();

        jPanel2.add(tu);
    }//GEN-LAST:event_new_FileMenuActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch(jComboBox1.getSelectedIndex())
        {
           
              
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void new_reqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_reqActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tu.getModel();
        LeftPaneUI lp1 = new LeftPaneUI();
        dtm.insertRow(1, new Object[][]{{ }});
        
        tu.getColumnModel().getColumn(0).setCellRenderer(lp1);
        tu.getColumnModel().getColumn(0).setCellEditor(lp1);
       
    }//GEN-LAST:event_new_reqActionPerformed
    public static void addElements(int type)
    {
        System.out.println("comes here");
        tu.setRequirementTemplate(type);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem close_FileMenu;
    private javax.swing.JButton del_req;
    private javax.swing.JMenu edit_menu;
    private javax.swing.JMenuItem exit_FileMenu;
    private javax.swing.JMenu file_menu;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem new_FileMenu;
    private javax.swing.JButton new_req;
    private javax.swing.JMenuItem open_FileMenu;
    private javax.swing.JMenuItem saveAs_FileMenu;
    private javax.swing.JMenuItem save_FileMenu;
    private javax.swing.JMenu tools_menu;
    // End of variables declaration//GEN-END:variables
}
